// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3-nKbYBQvy-1z-tO7rAtYEG2nTJCKYQ',
    appId: '1:556693094180:web:e95ca5000b4a9984db3db1',
    messagingSenderId: '556693094180',
    projectId: 'itc-fsktm',
    authDomain: 'itc-fsktm.firebaseapp.com',
    storageBucket: 'itc-fsktm.firebasestorage.app',
    measurementId: 'G-328X34PH58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTaqON5iPwY_l7TC97kbZxZaiaoYrco74',
    appId: '1:556693094180:android:5a4b2682eef8d8f5db3db1',
    messagingSenderId: '556693094180',
    projectId: 'itc-fsktm',
    storageBucket: 'itc-fsktm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Th8HbFLIsUCF4eJ_RXh3VZbsMW7tSUc',
    appId: '1:556693094180:ios:f229b393c021f9a1db3db1',
    messagingSenderId: '556693094180',
    projectId: 'itc-fsktm',
    storageBucket: 'itc-fsktm.firebasestorage.app',
    iosBundleId: 'com.fsktm.itcDebugAndDevelop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Th8HbFLIsUCF4eJ_RXh3VZbsMW7tSUc',
    appId: '1:556693094180:ios:f229b393c021f9a1db3db1',
    messagingSenderId: '556693094180',
    projectId: 'itc-fsktm',
    storageBucket: 'itc-fsktm.firebasestorage.app',
    iosBundleId: 'com.fsktm.itcDebugAndDevelop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg3-nKbYBQvy-1z-tO7rAtYEG2nTJCKYQ',
    appId: '1:556693094180:web:b2e48b61ddd62b71db3db1',
    messagingSenderId: '556693094180',
    projectId: 'itc-fsktm',
    authDomain: 'itc-fsktm.firebaseapp.com',
    storageBucket: 'itc-fsktm.firebasestorage.app',
    measurementId: 'G-219F5LBNTF',
  );
}
